### ISSUE TITLE
Expressions error

### ISSUE THREAD

**Issue by itsacoderepo** [bdcht/amoco#59]
Hi,

i followed the example and got 

```
>>> from amoco.arch.x86.env import *
>>> from amoco.cas import smt
>>> z = (eax^cst(0xcafebabe,32))+(ebx+(eax>>2))
>>> print z
T32
>>> print z.to_smtlib()
_top
>>> type(z)
<class 'amoco.cas.expressions.top'>
>>> z.to_smtlib().sexpr()
'_top'
```

It should be op. I removed "+(eax":

```
>>> z = (eax^cst(0xcafebabe,32))+(ebx>>2)
>>> type(z)
<class 'amoco.cas.expressions.op'>
>>> z.to_smtlib()
(eax ^ 3405691582) + LShR(ebx, 2)
>>> z.to_smtlib().sexpr()
'(bvadd (bvxor eax #xcafebabe) (bvlshr ebx #x00000002))'
```

**Comment by bdcht** [comment]
This is not really an error, its a feature ;) Well, this behavior was due to the default complexity threshold value set in amoco.config, which tends to simplify expressions aggressively, trading precision for speed in CFG recovery classes (mainly lbackward).
I have now increased the default value and set a lowered threshold only within lbackward class (commit 90f1c58).

Note that you can set this threshold to float('infinity') to always avoid this behavior. Just do:

> > > amoco.cas.expressions.configure(complexity=float('infinity'))
