### ISSUE TITLE
assignments to sliced constants 

### ISSUE THREAD

**Issue by ghost** [bdcht/amoco#79]
Hi Axel, 

was just playing around with the arm module when I saw this for the movz semantic:
```
      fmap[pc] = fmap[pc]+i.length
      result = cst(0,i.d.size)
      result[0:16] = i.imm
      fmap[i.d] = result
```

result[0:16] does not update `result`

assignments to sliced constants don't seem to work at all.
maybe intended? 

fast workaround right now is:
``` 
result = cst(i.imm.v, 16)
result = result.zeroextend(i.d.size)
```
Best
Behrad

**Comment by bdcht** [comment]
thanks for the report. 
Its indeed a common mistake...fixed in many archs but obviously not in armv8.
(Unfortunately I have not found a way to make the expressions api simpler and avoid these quirks.
The only way to assign to sliced expressions is when the expression is of comp type!)

I should probably undef the exp.__setitem__ method to at least detect this properly rather than ignore the assignment silently...

Fixed in next (big) release, end of august.

Meanwhile, your workaround is fine, could be simplified i guess as 
result = i.imm.zeroextend(i.d.size) which builds a comp object and eventually simplify it to a cst if possible.
thx

**Comment by ghost** [comment]
Nice, 
looking forward to the new release. 
thank you, Axel
